import type { Metadata } from "next";
import { Poppins, Kodchasan } from "next/font/google";
import "@/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { ptBR } from "@clerk/localizations";
import { auth } from "@clerk/nextjs/server";
import Header from "@/components/Header";
import HeaderPermittedSystem from "@/components/HeaderPermittedSystem";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const kodchasan = Kodchasan({
  variable: "--font-kodchasan",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();

  return (
    <ClerkProvider
      localization={ptBR}
      appearance={{
        // Desabilita as páginas padrão do Clerk
        elements: {
          rootBox: "w-full h-full",
        },
      }}
    >
      <html lang="en">
        <body
          className={`${poppins.variable} ${kodchasan.variable} antialiased`}
        >
          {userId ? <Header /> : <HeaderPermittedSystem />}
          <Toaster richColors />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
