import type { Metadata } from "next";
import { Poppins, Kodchasan } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "sonner";
import Header from "@/components/Header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const kodchasan = Kodchasan({
  variable: "--font-kodchasan",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${kodchasan.variable} antialiased`}>
        <Header />
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
