import type { Metadata } from "next";
import { Poppins, Kodchasan } from "next/font/google";
import { redirect } from "next/navigation";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { ptBR } from "@clerk/localizations";
import { Toaster } from "sonner";
import "@/styles/globals.css";
import Header from "@/components/Header";
import { Hydrate } from "@/components/Hydrate";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const kodchasan = Kodchasan({
  variable: "--font-kodchasan",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Verifica se o usuário está autenticado
  const { userId } = await auth();

  // Se o usuário não estiver autenticado, redireciona para a página de login
  if (!userId) {
    redirect("/login");
  }

  return (
    <ClerkProvider
      // Passa a localização para o Clerk para traduzir as mensagens
      localization={ptBR}
      // Configuração de aparência do Clerk para desabilitar as páginas padrão
      appearance={{
        elements: {
          rootBox: "w-full h-full",
        },
      }}
    >
      <html lang="en">
        <body
          className={`${poppins.variable} ${kodchasan.variable} antialiased`}
        >
          <Header />
          <Hydrate>{children}</Hydrate>
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
